mod 'puppetlabs-stdlib', '4.25.1'
mod 'puppetlabs-concat', '4.2.1'
mod 'puppetlabs-git', '0.5.0'
mod 'ghoneycutt-dnsclient', '3.5.2'
mod 'saz-ssh', '4.0.0'
mod 'maestrodev-wget', '1.7.3'
mod 'scottyc-golang', '2.0.3'
mod 'frozenfoxx-vundle', '0.1.2'
